#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import tomllib

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "target" / "TARGET.toml"
REPORTS = ROOT / "reports"
TOOL = REPORTS / "tool-output"
FINDINGS = ROOT / "findings"
WORK = ROOT / "work"
OUT_JSON = TOOL / "firmware-postrun-check.json"
OUT_TXT = TOOL / "firmware-postrun-check.txt"
REQUIRED_FINDINGS = ("inventory.md", "attack-surface.md", "secrets.md", "update-security.md", "findings.md", "coverage.md", "research.md", "analysis-log.md")


def load_json(path: Path, errors: list[str]):
    try:
        return json.loads(path.read_text())
    except Exception as exc:
        errors.append(f"invalid/missing JSON {path.relative_to(ROOT)}: {exc}")
        return None


def baseline_tool_sha256() -> str:
    digest = hashlib.sha256()
    tools = ROOT / "tools"
    for path in (tools / "firmware_baseline_core.py", tools / "firmware_baseline_enrich.py"):
        if path.is_file():
            digest.update(path.name.encode("utf-8") + b"\0" + path.read_bytes())
    return digest.hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def add_check(checks: list[dict], name: str, status: str, detail: str) -> None:
    checks.append({"name": name, "status": status, "detail": detail})


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []
    checks: list[dict] = []
    try:
        cfg = tomllib.loads(TARGET.read_text())
    except Exception as exc:
        errors.append(f"cannot read target/TARGET.toml: {exc}")
        cfg = {}

    if not cfg.get("engagement", {}).get("authorized", False):
        errors.append("engagement.authorized is not true")

    firmware_raw = cfg.get("firmware", {}).get("path")
    firmware_path = ROOT / str(firmware_raw) if firmware_raw else None
    prep = load_json(TOOL / "firmware-preparation.json", errors)
    baseline = load_json(TOOL / "firmware-baseline.json", errors)
    if firmware_path and firmware_path.is_file() and prep:
        actual = sha256_file(firmware_path)
        prepared = str(prep.get("sha256") or "")
        stored_path = TOOL / "firmware.sha256"
        stored = stored_path.read_text().split()[0].strip() if stored_path.is_file() and stored_path.read_text().strip() else ""
        if actual == prepared == stored:
            add_check(checks, "firmware-hash", "PASS", actual)
        else:
            errors.append(f"firmware hash mismatch actual={actual} preparation={prepared} stored={stored}")
    else:
        errors.append("configured firmware image or preparation hash is unavailable")

    if isinstance(baseline, dict):
        recorded = str((baseline.get("baseline_enrichment") or {}).get("tool_sha256") or "")
        current = baseline_tool_sha256()
        if recorded and recorded == current:
            add_check(checks, "baseline-provenance", "PASS", current)
        elif recorded:
            errors.append("deterministic baseline was generated by different baseline tool code; refresh firmware_baseline.py")
        else:
            errors.append("deterministic baseline lacks baseline_enrichment tool provenance; refresh firmware_baseline.py")

    final_report = REPORTS / "STATIC_SECURITY_REPORT.md"
    if final_report.is_file() and final_report.stat().st_size > 100:
        add_check(checks, "final-report", "PASS", str(final_report.relative_to(ROOT)))
    else:
        errors.append("reports/STATIC_SECURITY_REPORT.md missing or empty")

    missing_durable = [name for name in REQUIRED_FINDINGS if not (FINDINGS / name).is_file() or (FINDINGS / name).stat().st_size < 10]
    if missing_durable:
        errors.append("missing/empty durable findings: " + ", ".join(missing_durable))
    else:
        add_check(checks, "durable-records", "PASS", f"{len(REQUIRED_FINDINGS)} required records present")

    secret_cfg = cfg.get("secrets", {}) if isinstance(cfg, dict) else {}
    groups_doc = load_json(TOOL / "firmware-secret-groups.json", errors)
    if secret_cfg.get("ai_plausibility_triage", False) and isinstance(groups_doc, dict):
        expected_ids = {str(item.get("group_id")) for item in groups_doc.get("groups", []) if item.get("group_id")}
        review = REPORTS / "subagents" / "firmware-secrets-review.md"
        if not review.is_file():
            errors.append("AI secret triage enabled but reports/subagents/firmware-secrets-review.md is missing")
        else:
            text = review.read_text(encoding="utf-8", errors="replace")
            observed_ids = set(re.findall(r"\bFG-[0-9a-fA-F]{8,}\b", text))
            missing_ids = sorted(expected_ids - observed_ids)
            if "Completion: COMPLETE" not in text:
                errors.append("firmware-secrets-review.md lacks Completion: COMPLETE marker")
            if missing_ids:
                errors.append(f"secret triage artifact covers {len(observed_ids & expected_ids)}/{len(expected_ids)} groups; missing {len(missing_ids)}")
            if not missing_ids and "Completion: COMPLETE" in text:
                add_check(checks, "secret-group-coverage", "PASS", f"{len(expected_ids)}/{len(expected_ids)} semantic groups evidenced")

    ghidra_logs = sorted(TOOL.glob("ghidra-*.log"))
    ledger_path = WORK / "ghidra" / "budget.json"
    if ghidra_logs:
        ledger = load_json(ledger_path, errors)
        if isinstance(ledger, dict):
            entries = ledger.get("entries", [])
            attempts = [entry for entry in entries if entry.get("counts_toward_budget", True)]
            analysis = cfg.get("analysis", {})
            hyp_cap = int(analysis.get("max_ghidra_slices_per_hypothesis", 3))
            bin_cap = int(analysis.get("max_ghidra_slices_per_binary", max(hyp_cap, 6)))
            total_cap = int(analysis.get("max_ghidra_slices_per_assessment", max(bin_cap, 12)))
            by_hyp: dict[str, int] = {}
            by_bin: dict[str, int] = {}
            for entry in attempts:
                hyp = str(entry.get("hypothesis_id") or "UNSPECIFIED")
                binary = str(entry.get("binary") or "UNKNOWN")
                by_hyp[hyp] = by_hyp.get(hyp, 0) + 1
                by_bin[binary] = by_bin.get(binary, 0) + 1
            over_hyp = {k: v for k, v in by_hyp.items() if v > hyp_cap}
            over_bin = {k: v for k, v in by_bin.items() if v > bin_cap}
            if over_hyp:
                errors.append(f"Ghidra hypothesis budget exceeded: {over_hyp}")
            if over_bin:
                errors.append(f"Ghidra binary budget exceeded: {over_bin}")
            if len(attempts) > total_cap:
                errors.append(f"Ghidra assessment budget exceeded: {len(attempts)} > {total_cap}")
            if not over_hyp and not over_bin and len(attempts) <= total_cap:
                add_check(checks, "ghidra-budgets", "PASS", f"attempts={len(attempts)} caps={hyp_cap}/{bin_cap}/{total_cap}")
    else:
        add_check(checks, "ghidra-budgets", "PASS", "no Ghidra attempts recorded")

    if final_report.is_file():
        report_text = final_report.read_text(encoding="utf-8", errors="replace")
        if "Highest confirmed" not in report_text:
            errors.append("final report lacks explicit highest confirmed severity")
        if re.search(r"(?i)highest supported severity", report_text):
            errors.append("final report uses prohibited 'highest supported severity' wording")

    findings_path = FINDINGS / "findings.md"
    if findings_path.is_file():
        findings_text = findings_path.read_text(encoding="utf-8", errors="replace")
        important = bool(re.search(r"(?im)^###\s+F-[^\n]*(?:Critical|High)", findings_text))
        validators = list((REPORTS / "subagents").glob("validator*.md"))
        if important and not validators:
            errors.append("High/Critical candidate or finding exists without validator artifact")
        elif important:
            add_check(checks, "independent-validation", "PASS", f"{len(validators)} validator artifact(s)")

    analysis_log = FINDINGS / "analysis-log.md"
    if analysis_log.is_file():
        text = analysis_log.read_text(encoding="utf-8", errors="replace")
        step_limited = len(re.findall(r"(?i)step-limited", text))
        if step_limited:
            warnings.append(f"analysis log records {step_limited} step-limited delegated task(s)")
        for line in text.splitlines():
            if not line.startswith("|") or "reports/subagents/" not in line:
                continue
            match = re.search(r"`(reports/subagents/[^`]+)`", line)
            if not match:
                continue
            artifact = ROOT / match.group(1)
            if not artifact.is_file():
                errors.append(f"delegation log references missing artifact: {match.group(1)}")
                continue
            artifact_text = artifact.read_text(encoding="utf-8", errors="replace")
            if "Completion: COMPLETE" not in artifact_text:
                errors.append(f"delegated artifact lacks Completion: COMPLETE: {match.group(1)}")
        m = re.search(r"Observed peak delegated tasks:\s*(\d+)", text)
        cap = int(cfg.get("orchestration", {}).get("max_parallel_agents", 2))
        if m and int(m.group(1)) > cap:
            errors.append(f"observed delegated concurrency {m.group(1)} exceeds configured cap {cap}")

    research_dir = REPORTS / "research"
    question_artifacts = [p for p in research_dir.glob("*.md") if p.name != ".gitkeep"] if research_dir.is_dir() else []
    research_cap = int(cfg.get("orchestration", {}).get("research_max_questions", 5))
    if len(question_artifacts) > research_cap:
        errors.append(f"research question artifact count {len(question_artifacts)} exceeds configured cap {research_cap}")

    status = "PASS" if not errors else "FAIL"
    result = {"schema_version": 1, "status": status, "checks": checks, "warnings": warnings, "errors": errors}
    TOOL.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    lines = [f"Firmware post-run invariant check: {status}"]
    lines.extend(f"PASS: {item['name']}: {item['detail']}" for item in checks)
    lines.extend(f"WARN: {item}" for item in warnings)
    lines.extend(f"FAIL: {item}" for item in errors)
    OUT_TXT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    return 0 if status == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
