#!/usr/bin/env bash
SAT_CATALOG="$ROOT/dependencies/catalog.toml"
sat_sudo(){ if [[ $(id -u) -eq 0 ]]; then "$@"; else sudo "$@"; fi; }
sat_catalog(){ python3 - "$SAT_CATALOG" "$1" "$2" <<'P'
import sys,tomllib
p,d,f=sys.argv[1:]
with open(p,'rb') as h:v=tomllib.load(h)['dependencies'][d].get(f,'')
print('\n'.join(v) if isinstance(v,list) else v)
P
}
sat_check_dependency(){ local c; c="$(sat_catalog "$1" check)"; PATH="$SAT_HOME/bin:$PATH" bash -lc "$c" >/dev/null 2>&1; }
sat_doctor_dependency(){ sat_check_dependency "$1" && printf '  ✓ %s\n' "$1" || printf '  ✗ %s\n' "$1"; }
sat_install_apt(){ mapfile -t p < <(sat_catalog "$1" packages); sat_sudo apt-get update; sat_sudo apt-get install -y "${p[@]}"; }
sat_install_dependency(){ local d="$1" k h; sat_check_dependency "$d" && { echo "[=] $d"; return; }; k="$(sat_catalog "$d" kind)"; echo "[+] $d"; if [[ "$k" == apt ]]; then sat_install_apt "$d"; else h="$(sat_catalog "$d" handler)"; "$h" "$d"; fi; sat_check_dependency "$d" || { echo "Install check failed: $d" >&2; return 1; }; }
install_opencode(){ mkdir -p "$SAT_HOME/bin"; curl -fsSL https://opencode.ai/install | OPENCODE_INSTALL_DIR="$SAT_HOME/bin" bash; }
install_uv(){ mkdir -p "$SAT_HOME/bin"; curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="$SAT_HOME/bin" sh; }
install_python_tool(){ local d="$1" p e; p="$(sat_catalog "$d" package)"; e="$(sat_catalog "$d" executable)"; sat_install_dependency uv; "$SAT_HOME/bin/uv" tool install --force --python 3.12 "$p"; local f; f="$(PATH="$HOME/.local/bin:$PATH" command -v "$e" 2>/dev/null || true)"; [[ -z "$f" ]] || ln -sf "$f" "$SAT_HOME/bin/$e"; }
install_jdk21(){ mkdir -p "$SAT_HOME/java" "$SAT_HOME/bin" "$SAT_HOME/cache"; local a u z d; case "$(uname -m)" in x86_64) a=x64;; aarch64|arm64) a=aarch64;; *) return 1;; esac; u="$(curl -fsSL "https://api.adoptium.net/v3/assets/latest/21/hotspot?architecture=$a&image_type=jdk&os=linux&vendor=eclipse" | python3 -c 'import json,sys;print(json.load(sys.stdin)[0]["binary"]["package"]["link"])')"; z="$SAT_HOME/cache/jdk21.tgz"; curl -fL "$u" -o "$z"; rm -rf "$SAT_HOME/java/jdk-21" "$SAT_HOME/java/x"; mkdir -p "$SAT_HOME/java/x"; tar -xzf "$z" -C "$SAT_HOME/java/x"; d="$(find "$SAT_HOME/java/x" -mindepth 1 -maxdepth 1 -type d | head -1)"; mv "$d" "$SAT_HOME/java/jdk-21"; rm -rf "$SAT_HOME/java/x"; ln -sf "$SAT_HOME/java/jdk-21/bin/java" "$SAT_HOME/bin/java"; }
install_ghidra(){ sat_install_dependency jdk21; mkdir -p "$SAT_HOME/tools" "$SAT_HOME/cache" "$SAT_HOME/bin"; local u z d; u="$(curl -fsSL https://api.github.com/repos/NationalSecurityAgency/ghidra/releases/latest | python3 -c 'import json,sys;d=json.load(sys.stdin);print(next(a["browser_download_url"] for a in d["assets"] if a["name"].endswith(".zip")))')"; z="$SAT_HOME/cache/ghidra.zip"; curl -fL "$u" -o "$z"; rm -rf "$SAT_HOME/tools/ghidra" "$SAT_HOME/tools/x"; mkdir -p "$SAT_HOME/tools/x"; unzip -q "$z" -d "$SAT_HOME/tools/x"; d="$(find "$SAT_HOME/tools/x" -mindepth 1 -maxdepth 1 -type d | head -1)"; mv "$d" "$SAT_HOME/tools/ghidra"; rm -rf "$SAT_HOME/tools/x"; ln -sf "$SAT_HOME/tools/ghidra/support/analyzeHeadless" "$SAT_HOME/bin/analyzeHeadless"; }
install_jadx(){ sat_install_dependency jdk21; mkdir -p "$SAT_HOME/tools/jadx" "$SAT_HOME/cache" "$SAT_HOME/bin"; local u; u="$(curl -fsSL https://api.github.com/repos/skylot/jadx/releases/latest | python3 -c 'import json,sys;d=json.load(sys.stdin);print(next(a["browser_download_url"] for a in d["assets"] if a["name"].startswith("jadx-") and a["name"].endswith(".zip")))')"; curl -fL "$u" -o "$SAT_HOME/cache/jadx.zip"; rm -rf "$SAT_HOME/tools/jadx"; mkdir -p "$SAT_HOME/tools/jadx"; unzip -q "$SAT_HOME/cache/jadx.zip" -d "$SAT_HOME/tools/jadx"; ln -sf "$SAT_HOME/tools/jadx/bin/jadx" "$SAT_HOME/bin/jadx"; }
install_apktool(){ sat_install_dependency jdk21; mkdir -p "$SAT_HOME/tools/apktool" "$SAT_HOME/bin"; local u; u="$(curl -fsSL https://api.github.com/repos/iBotPeaches/Apktool/releases/latest | python3 -c 'import json,sys;d=json.load(sys.stdin);print(next(a["browser_download_url"] for a in d["assets"] if a["name"].startswith("apktool_") and a["name"].endswith(".jar")))')"; curl -fL "$u" -o "$SAT_HOME/tools/apktool/apktool.jar"; printf '#!/usr/bin/env bash\nexec "%s/bin/java" -jar "%s/tools/apktool/apktool.jar" "$@"\n' "$SAT_HOME" "$SAT_HOME" > "$SAT_HOME/bin/apktool"; chmod +x "$SAT_HOME/bin/apktool"; }
install_rust(){ mkdir -p "$SAT_HOME/rust" "$SAT_HOME/bin"; export RUSTUP_HOME="$SAT_HOME/rust/rustup" CARGO_HOME="$SAT_HOME/rust/cargo"; curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --no-modify-path; ln -sf "$CARGO_HOME/bin/cargo" "$SAT_HOME/bin/cargo"; ln -sf "$CARGO_HOME/bin/rustc" "$SAT_HOME/bin/rustc"; }
install_binwalk(){ sat_install_dependency rust; export RUSTUP_HOME="$SAT_HOME/rust/rustup" CARGO_HOME="$SAT_HOME/rust/cargo"; "$CARGO_HOME/bin/cargo" install binwalk --force --root "$SAT_HOME"; }
sat_install_core(){ for d in ca-certificates curl python3 unzip; do sat_install_dependency "$d"; done; sat_install_dependency opencode; sat_install_dependency uv; }
